### ISSUE TITLE
Extension conflict: Bypass Paywall

### ISSUE THREAD

**Issue by ShintoPlasm** [mikeyaworski/ABS#29]
I've noticed that the spoofing option has a specific extension conflict in Opera (but not in EdgeC, Chrome, Brave or Vivaldi): the spoofing mode doesn't work when Bypass Paywall (https://github.com/iamadamdev/bypass-paywalls-chrome) is installed in Opera.

When running automated searches, while the search rewards tally up as expected, the Edge-specific tally remains on zero for both the 'desktop' and 'mobile device' categories. This only happens when the Bypass Paywall extension is enabled in Opera (irrespective of which paywalled websites are enabled/disabled in that extension's options).

I'm using Opera Stable 71.0.3770.271 on Windows 10 x64. I have eliminated all other extension conflicts; only ABS and Bypass Paywall appear to conflict in Opera when both are enabled.

I've not been able to open an Issue on Bypass Paywall's Github as the dev seems to limit who can submit a bug report.

Thank you.

**Comment by mikeyaworski** [comment]
I appreciate the detail you've included!

Unfortunately, I don't believe there's anything that can be done about this (from either of the extensions). I assume this is a deficiency of Opera. What both extensions are doing is modifying the request headers (ABS is doing this to spoof `User-Agent`). Now, it seems like Opera is only allowing one of the extensions to modify the headers, or they're letting ByPass Paywall take precedence over ABS.

It's that, or the fact that ByPass Paywall pushes a `User-Agent` header, rather than modifying the existing one, and then Opera treats duplicate headers differently than other browsers.

I'll test if pushing a duplicate header vs modifying the existing one will solve the issue, but I can't promise that it will help. I'll get to this when I have time in the coming weeks, and I'll close + comment on this issue once I've done so.

**Comment by ShintoPlasm** [comment]
I've now managed to open an issue at the other dev's page.

**Comment by mikeyaworski** [comment]
I think the best solution is to either not use Opera, or disable ByPass Paywall while doing your searches. If you can disable ByPass Paywall specifically on this site that we are performing searches on, that would be all that you need to avoid this issue.

**Comment by ShintoPlasm** [comment]
Fair enough. BP's dev also closed the issue on his end. I've submitted a bug report to Opera, for the record.
I personally switch between browsers and Opera is not my main driver anyway - but it was worth looking into.
Thanks for your time! 👍
