### ISSUE TITLE
Add sync for This or That answers

### ISSUE THREAD

**Issue by TaherPatan** [mikeyaworski/ABS#36]
Hello, I think a good feature would be to add an option to sync the options of this or that to some cloud directory so that most of the times the bot auto learns answers and answers them correctly for other people that get the same questions, it would increase overall earning more points for everyone.

**Comment by mikeyaworski** [comment]
This is understandable, but getting 100% of those answers correct (and instantaneously) would be a huge red flag. Discretion is best here. If you really want to get 100% correct answers, you have two options:

1. Disable the random guessing and manually search the answers
2. This may or may not still work (I haven't tried in a few months): either shrink your screen to mobile size and open the quiz or just start a bunch of mobile searches and then start the quiz in a new tab. It may have been patched, but a few months ago, the mobile view leaked the correct answers, so this extension was able to choose the correct ones.

I'm going to close this issue because:

- It would be a lot of work to maintain
- It would introduce remote code, which people generally are not comfortable with due to potential malware
- In my opinion, this would flag your account and is not worth micro managing those points

We can re-open this in the future if someone suggests, or I think of, and alternate solution. And I want to note that random click rates should be introduced first (we do not want to *instantly* get all correct answers): #10
