### ISSUE TITLE
Extension just stopped working

### ISSUE THREAD

**Issue by siky112** [mikeyaworski/ABS#45]
I tried to run this today and it didn't work when I pressed "Start Searches". None of the settings saved, either. I tried uninstalling and reinstalling, but it just won't work.

**Comment by mikeyaworski** [comment]
By "didn't work", I assume you mean that the button did nothing?

Which browser are you using?

**Comment by siky112** [comment]
I'm using edge. And yeah, nothing happened when I clicked the button.

**Comment by mikeyaworski** [comment]
Okay would you mind going to `edge://extensions/` in your address bar, find ABS and see if there is a red box that says "Errors". If there is, please screenshot or copy/paste the message. If not, let me know.

Extension works for my on all browsers, but I'll try to see if there is an error on yours.

**Comment by siky112** [comment]
There is no red box. Nothing.

**Comment by siky112** [comment]
I turned on Collect Errors, but nothing is happening when I click search.

**Comment by mikeyaworski** [comment]
Could you try the extension in another browser and see if it works?

And after that, can you tell me which version of Edge you're using?

**Comment by siky112** [comment]
I can't use another browser, and I'm using the latest version of Edge.

**Comment by mikeyaworski** [comment]
Hmm. It's probably something to do with your browser setup. I'll give some technical instructions because it's the only way to get info.

1. Go to `edge://extensions/`
2. Enable `Developer mode` at the bottom left
3. Click `Background page` in the ABS extension.
4. Go back to the other Edge window, create a new tab and search.
5. Open the other Edge window and see if there is anything printed in the console. It should look like this (might be white for you, if you don't use dark mode):
![image](https://user-images.githubusercontent.com/10966214/105098806-a245f080-5a78-11eb-9611-35e7dec28442.png)

If there's nothing there, then do this:

1. Open a new tab
2. Press `Ctrl + Shift + J` and it should open the same sort of console as in the screenshot above.
3. Start searches in that tab and see what the console says.

Hopefully there's something in one of the consoles. Let me know.

**Comment by siky112** [comment]
Oh, I was looking in the wrong spot.
![abs](https://user-images.githubusercontent.com/20342336/105109354-3ca23600-5a71-11eb-82d7-927cd00b4ec4.PNG)

**Comment by mikeyaworski** [comment]
Okay cool. Are you able to follow steps 1-5 in my previous message so that I can get more specific information about the error? I'm not able to reproduce this myself. Also, would you mind screenshotting your settings?

**Comment by siky112** [comment]
I restarted Edge and it started working again. No clue why, but until this is fixed, I can't help you much more.

**Comment by mikeyaworski** [comment]
Interesting. Okay if you don't run into this again in next week or so, I'll close the ticket. But if it ever happens again, even after that, feel free to comment here again and I'll try to resolve it.
