### ISSUE TITLE
Difference Between Blitz Search and Normal

### ISSUE THREAD

**Issue by ledfordd39** [mikeyaworski/ABS#46]
Hello,

I have been using this addon for a while and I am finding it very helpful.

1) However, something that is not clear to me is the difference between blitz search and, let's say, random search time between 0ms and 200ms. Which is safer and which is faster/more efficient?

2) Also, would it matter if I keep both 0-200ms and blitz search at the same time?

3) Does blitz search always use the same speed? How is the speed decided? 

4) Under which conditions do blitz searches count towards the rewards search count? 

5) Is it too risky to use compared to just 0-200ms?

I tried looking for more info on this on the internet but found nothing at all.

I don't know how to use GitHub, so I hope this doesn't count as spam. It is just a piece of info that is not documented anywhere and think might interest other users.

Thanks and keep up the good work

**Comment by bbzlazer** [comment]
I personally use 1000-2000 ms, that works best for me. Any faster and it starts to register slowly. 

Just a question, how fast can you personally go when it starts to stop registering?

**Comment by mikeyaworski** [comment]
1. All blitz search does is start timer immediately after the search fires. Non-blitz will wait for the search to be fully loaded and *then* start the timer. So what's the difference? I guess it just depends how long your browser / internet / Msoft take to completely load the search. Which is safer? Both are fine, but technically non-blitz. Which is faster? Blitz. Which is more efficient? Non-blitz, since all the searches should actually register.
2. Yes, it would matter. Don't do that that. If you put blitz and 0ms, it'll spam all searches at the same time and probably none of them will register.
3. See 1 for explanation on blitz vs not blitz. But blitz is not a speed - it just determines when to start the timer between searches.
4. Not exactly sure, but it depends on how Msoft registers the searches. I would say the condition is if your delay is long enough such that the page actually loads, despite using Blitz. IMO you should never use blitz (I only made it as a feature request).
5. I would say they're similar risk levels, but I would recommend not using blitz for consistency / technically less risk.

**Comment by mikeyaworski** [comment]
> Just a question, how fast can you personally go when it starts to stop registering?

Not sure if you're asking me or OP, but I use random search delays (and I never use blitz). My random search delays are something like between 2-15 seconds, and I just let it run in the background on daily schedule. I don't try to get it done fast.

**Comment by ledfordd39** [comment]
@bbzlazer The absolute fastest you can go with all searches registering according to my tests would be 200 to 200 ms with blitz. You will need to up your query amount by an additional 2/3 if you do that or most searches will not count. You can tweak this if you wanna be a bit safer.

@mikeyaworski Thanks for your help 👍
