### ISSUE TITLE
VPN problem

### ISSUE THREAD

**Issue by OverVault** [mikeyaworski/ABS#54]
Hi:

So i started using this extension ( which is awsome by the way, thank you), and saw a video on youtube showing how you can even change your country with a vpn to earn more points, but some countries like france or italy it didnt work.

I do both researchs, the web and the mobile one and it didnt count them, it only count the 12 point you get from edge nithing else.

The normal and daily points work fine in most ocuntries only the research point didnt work, and in some countries like USA it work fine.

Is there a way to fix it? thank you.

**Comment by mikeyaworski** [comment]
Unfortunately, I don't think there is a way to fix this. It depends on Microsoft and how they determine where the request is coming from. Some VPNs may work, others may not. I've noticed similar issues where I have to turn my VPN off, even though I'm VPNing to where I actually live (Canada).

Also, be careful of using a VPN because it's against the rules and easy to detect.
